require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# iOS 15.0+ para React Native 0.73.6
platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false
use_modular_headers!

target 'MrPlan' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Deshabilitar Hermes para mayor estabilidad con Xcode 16
    :hermes_enabled => false,
    # Deshabilitar Fabric (New Architecture) para mayor estabilidad
    :fabric_enabled => false,
    # Configurar app path
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

# Tests target removed - not present in project

  post_install do |installer|
    # React Native post install
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Configuraciones específicas para Xcode 16 y iOS 15+
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # iOS Deployment Target uniforme
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        
        # Configuraciones para Xcode 16
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'NO'
        
        # Configuraciones de arquitectura
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64' if ENV['CI']
        
        # Configuraciones adicionales para estabilidad
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        
        # Configuraciones específicas para React Native 0.73
        config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC'
        config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) $(SRCROOT)/../node_modules/react-native/ReactCommon'
        
        # Evitar warnings específicos de Xcode 16
        config.build_settings['CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED'] = 'NO'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      end
    end
    
    # Configuración adicional para targets específicos
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end